### ISSUE TITLE
GFSearchBar is not working on web

### ISSUE THREAD

**Issue by explodus** [ionicfirebaseapp/getwidget#112]
onItemSelected is not called

attached the example to see it without debugging

[searchbar.dart.txt](https://github.com/ionicfirebaseapp/getflutter/files/4274930/searchbar.dart.txt)

**Comment by PietechSolution** [comment]
Hello @explodus 

Do u have an issue with Mobile or only web?

Thanks.

**Comment by explodus** [comment]
Hey @PietechSolution it affected only the web build. Mobile is working fine.

**Comment by PietechSolution** [comment]
ok, we will around our web demo and update.

**Comment by explodus** [comment]
thanks, i will watch the issue, cause it affects my apps too, not only the web demo.

**Comment by code-gene** [comment]
@explodus 

We tested it and it is working fine on the web. We have also tested with your file which you provided and it is working fine with that too.

If you find any bug/issue in future please create a new issue, for now we are closing this.
