### ISSUE TITLE
How to be a contributor?

### ISSUE THREAD

**Issue by andriawan** [ionicfirebaseapp/getwidget#114]
Hello, I am a developer from Indonesia. It looks like this repository is very great. Recently, i use flutter as main mobile development in my office. I'm interested in contributing code on this repository. What should i do? is there any official guidance to be a contributor?

**Comment by PietechSolution** [comment]
You can join our slack 

https://join.slack.com/t/getflutterdev/shared_invite/enQtOTQ2MjM4NjA0ODIzLTI3NDlmZjNmNjMzMDQ5NzE1MTIxOWQ5NTNhMjNjZDkyZGE1NWQyMmVkN2EwNDA3ZjRiOGQwOTY1NjgxOGFhNGE

There we may have a discussion on how you can contribute to this project.
