### ISSUE TITLE
More social buttons

### ISSUE THREAD

**Issue by degloff** [ionicfirebaseapp/getwidget#116]
Would it be possible to add some more social media buttons? Targeting Asian platforms, such as Line and WeChat?

**Comment by code-gene** [comment]
This is in our roadmap.

**Comment by Abh1shekShinde** [comment]
Can we try to contribute by adding some new social media icons and buttons .

**Comment by prajyotBhoir** [comment]
Can we try to contribute?

**Comment by Atul-pietech** [comment]
hi, @prajyotBhoir yes you can if we find theme useful we would incorporate them,
take a fork and create a pull request from the fork itself.

**Comment by sarithavarrier** [comment]
hi @degloff ,we have included more social media buttons as per your suggestion,please try latest verison

Thank you
