### ISSUE TITLE
I want to see the demo, but there's nothing in the demo

### ISSUE THREAD

**Issue by zhuyonghao** [ionicfirebaseapp/getwidget#128]

**Comment by PietechSolution** [comment]
Which demo you mean ??

**Comment by PietechSolution** [comment]
If you looking for app demo checkout this repository :  https://github.com/ionicfirebaseapp/getflutter-app-kit

**Comment by birchb** [comment]
The demo uses getwidget: ^1.2.2. Will the demo be updated any time soon?
