### ISSUE TITLE
gradient value does not take Gradient().

### ISSUE THREAD

**Issue by findridoy** [ionicfirebaseapp/getwidget#131]
GFDrawer(
  gradient: Gradient() //error abstract classes can't be instantiated
)

why?

**Comment by japatel225** [comment]
> 
> 
> GFDrawer(
> gradient: Gradient() //error abstract classes can't be instantiated
> )
> 
> why?

That is because, like the error says, Gradient class is an abstract class and abstract classes cannot be instantiated directly. Try using a subclass of Gradient class, like LinearGradient for example.
