### ISSUE TITLE
Docs say about isScrollable  which is not supported

### ISSUE THREAD

**Issue by Purus** [ionicfirebaseapp/getwidget#132]
**Describe the bug**
Not sure this should be a feature request.. The regular TabBar supports `isScrollable` property to make the tabs scroll. The GFTabBar source code has few lines about this property but it's support is not present.

**Expected behavior**
`isScrollable` boolean property should be present.

**Smartphone :**
 - Device: Redmi Note 7 Pro
 - OS: Android 9

**Comment by deepikahr** [comment]
@Purus Hey, it will be fixed in our upcoming version
