### ISSUE TITLE
Avatar with Badge

### ISSUE THREAD

**Issue by rlee1990** [ionicfirebaseapp/getwidget#134]
The code does not match the displayed images. In GFAvatar there is not an option for badges.

**Comment by piyushbhatia891** [comment]
I will take a look at it

**Comment by rlee1990** [comment]
@piyushbhatia891 any updates?

**Comment by deepikahr** [comment]
@rlee1990 Hey, using GFIconBadge widget you can create avatar with badge. 

This is the sample code  :
const GFIconBadge(
                child: GFAvatar(
                  backgroundColor: GFColors.SUCCESS,
                ),
                counterChild: GFBadge(
                  text: '12',
                  shape: GFBadgeShape.circle,
                ),
              ), 

We will update our docs soon. Thank you

**Comment by rlee1990** [comment]
@deepikahr thanks it worked.
