### ISSUE TITLE
GFCarousel active page indicator is not being updated without "onPageChanged"

### ISSUE THREAD

**Issue by yasalkhatib** [ionicfirebaseapp/getwidget#139]
I noticed that the active page indicator is not being updated without explicitly call setState on onPageChanged callback.

Currently, if I need to update the active page indicator, I have to use GFCarousel inside a stateful widget and set onPageChanged,  
```
onPageChanged: (index){
        setState(() {});
},
```

**Comment by ngoctranfire** [comment]
Hey @yasalkhatib, I solved this by wrapping it in my own StatefulWidget and calling setState(). This is a limitation they have. Something that I am trying to figures out now is how to actually start the indicators at the right "startingPageIndex" if I set an initialPage = 5, and I have 6 items, I want the dots to show active indicator at the end. However, it isn't doing this for me.

**Comment by yasalkhatib** [comment]
That's correct you, need to wrap it in a stateful widget and then call setState({}) on onPageChanged callback. However, I believe, this is a bug and for sure is not the intended behavior.

**Comment by yasalkhatib** [comment]
Regarding your question about "startingPageIndex". I faced the same problem. After reading the code, I found that the current implementation of GFCarousel doesn't take into consideration the initalPageIndex and always sets the dot index to 0.

 I will open an issue with a solution for that.

**Comment by ngoctranfire** [comment]
@yasalkhatib, sure. I created an issue here: [#144](https://github.com/ionicfirebaseapp/getwidget/issues/144)

**Comment by deepikahr** [comment]
@yasalkhatib Hey, It will be fixed in upcoming version. Thank you
