### ISSUE TITLE
[GFCarousel] timer of the autoPlay is not disposed

### ISSUE THREAD

**Issue by yasalkhatib** [ionicfirebaseapp/getwidget#143]
**Describe the bug**
In GFCarousel, inside dispose method, 
  ```
@override
  void dispose() {
    super.dispose();
    timer?.cancel();
  }
```
The problem here is that super.dispose is being called first and because of that timer?.cancel(); will never be executed.

**Expected behavior**
timer should be disposed before calling super.dispose();

**Comment by deepikahr** [comment]
@yasalkhatib  Hey, It will be fixed in upcoming version. Thank you
