### ISSUE TITLE
GFCarousel initialPage Not Honored if Page Indicators Enabled.

### ISSUE THREAD

**Issue by ngoctranfire** [ionicfirebaseapp/getwidget#144]
**Describe the bug**

When we set an initialPage, it is not honored in the indicators. The indicator always starts at 0. It should not be the case.

**To Reproduce**
1. Create a GFCarousel
2. Set the initial page index to anything but 0.
3. Have active indicators to be true. Notice that the indicator's initial page index is not honored.

**Expected behavior**
The indicators should start in the right position with the initial page index honored.

**Additional context**
From the description on: #[139](ionicfirebaseapp).

**Comment by deepikahr** [comment]
@ngoctranfire Hey, It will be fixed in upcoming version. Thank you
