### ISSUE TITLE
[GFAppBar] clear button does not fire onChanged

### ISSUE THREAD

**Issue by zl910627** [ionicfirebaseapp/getwidget#149]
**Describe the bug**
`GFAppBar` with `searchBar: true`, it will show `x` button when search bar expanded.
If taps this button, search bar input would be cleared with collapsed.
But, even though text changed, no `onChanged` callback fired.

**To Reproduce**

```dart
GFAppBar(
        title: Text('Search'),
        searchBar: true,
        onChanged: onQueryChanged,
        searchBarColorTheme: Colors.black,
        searchHintStyle: Get.textTheme.headline1.apply(
          color: Colors.black,
        ),
      )
```
1. tap search magnifying button to expand
2. input something with checking `onChanged` works
3. tap `X` right side, to collapse search bar.
4. no `onChanged` fired
5. repeat step1 again to see what current input is (it would be empty.)

**Expected behavior**
At step3, we need to get `onChanged` with empty string
And / Or searchbar event for expand / collapse

**Comment by Abishek1997** [comment]
Yes, it needs to be fixed. Should be quite easy to do right? Could simply set the searchController to an empty string to reset the searchbar. Please look into it :)

**Comment by deepikahr** [comment]
@zl910627 Hey, x button is only for search bar expand / collapse purpose.
 
5.repeat step1 again to see what current input is (it would be empty.), this will be fixed in upcoming version
