### ISSUE TITLE
Screenshots and sample code are not same.

### ISSUE THREAD

**Issue by zl910627** [ionicfirebaseapp/getwidget#150]
https://docs.getwidget.dev/
For example, `GFListTile`
![image](https://user-images.githubusercontent.com/53897531/81909851-61e2c880-95f5-11ea-8a53-492e52a139f0.png)
As you can see, no `favorite` icon on screenshot even there is in code.
Sample code clip and screenshot is mismatch.
Need to be matched exactly, just like vuetify.

**Comment by deepikahr** [comment]
@zl910627 Hey, thanks for noticing, We will update our sample code in next version.
