### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by iamwilph** [ionicfirebaseapp/getwidget#152]
It's down since yesterday. Is there other way we can view the documentation or perhaps include the source code in the app itself and not just the link of the docs site.

**Comment by PietechSolution** [comment]
Hello,

We changing our main domain as have some issue with GETFLUTTER name on legal side.

You can view docs: https://docs.getwidget.dev/

Thanks.

**Comment by iamwilph** [comment]
Got it. Thank you.

**Comment by fringefilmsoz** [comment]
Is it possible to upate your readme with the new links please?
