### ISSUE TITLE
Table Widget

### ISSUE THREAD

**Issue by Prn-Ice** [ionicfirebaseapp/getwidget#155]
**Is your feature request related to a problem? Please describe.**
I see no Table widget in your previews or in the docs, something like [this](https://api.flutter.dev/flutter/widgets/Table-class.html).

**Describe the solution you'd like**
Is there a table widget currently, if not are there any plans for one.

**Comment by deepikahr** [comment]
@Prn-Ice Hey, currently we don't have Table widget. We are not planning to release Table Widget any time soon. Thank you
