### ISSUE TITLE
gf_Carousel Cannot read property 'Symbol(dartx.round)' of null

### ISSUE THREAD

**Issue by Bilonik** [ionicfirebaseapp/getwidget#157]
**Describe the bug**
Cannot read property 'Symbol(dartx.round)' of null
    at page_view.PageController.new.nextPage (http://localhost:60166/packages/flutter/src/widgets/page_view.dart.lib.js:330:42)
    at http://localhost:60166/packages/getwidget/components/carousel/gf_carousel.dart.lib.js:1031:38

**Comment by PietechSolution** [comment]
We have updated our package so install new version and let us know if you have any issues.

**Comment by Bilonik** [comment]
Hi,

After upgrading and Flutter Clean. 
Same Problem
