### ISSUE TITLE
[GFCheckbox] Checkbox isn't being disable when passed NULL to onChanged

### ISSUE THREAD

**Issue by bwysistemas** [ionicfirebaseapp/getwidget#158]
When I pass NULL to onChanged, to disable checkbox, it isn't being disable. By default, in the widget Checkbox (native of the flutter), when you pass NULL to "onChanged" it maintain the checkbox disabled with the defined value.

I think that is important disable the widget when is passed NULL to onChanged.

**Comment by deepikahr** [comment]
@bwysistemas That's fixed in an upcoming version

**Comment by PietechSolution** [comment]
This update available by weekend release
