### ISSUE TITLE
Back arrow  or any button next to TabBar View

### ISSUE THREAD

**Issue by rachidev84** [ionicfirebaseapp/getwidget#164]
I want to display tabbar view and arrow back in the horizontal line without display appbar
like this example

![tab](https://user-images.githubusercontent.com/24500191/90846327-d1d4bd80-e35f-11ea-9aa0-edf660fb8695.PNG)

or is there any way to add button next to tabbar when I click on this button I can navigat to other screen without display it on tabbarView,

**Comment by Sandipkakadiya** [comment]
HI @rachidev84 

i can not clearly understand what issue or problem you are facing. could clarify in more brief.
