### ISSUE TITLE
Wrong GFButton size.

### ISSUE THREAD

**Issue by zl910627** [ionicfirebaseapp/getwidget#165]
![image](https://user-images.githubusercontent.com/53897531/91630399-b888dc80-ea03-11ea-87f3-5b89828603b5.png)

If button is not `fullWidthButton` or `blockButton`, it would be same with `blockButton`.
In my opinion, it should be wrap content width with some padding.
Thank you

**Comment by Sandipkakadiya** [comment]
Yes. thank for pointing it out. we have kept note of it. it will be available in next release.

**Comment by Sandipkakadiya** [comment]
please update plugin to 1.2.2 and try we have fixed this issue.
Thank you,
