### ISSUE TITLE
On click event on images

### ISSUE THREAD

**Issue by sgarg15** [ionicfirebaseapp/getwidget#171]
**Is your feature request related to a problem? Please describe.**
I am trying to use the `GFImageOverlay`, but one of my main problems is that the image is not clickable. Since i wanted to have it so that when i click the image, it expands it, but since the `GFImageOverlay` does not support on click event, I can't do that

**Describe the solution you'd like**
Adding either `onClick` or `onTap` to the GFImageOverlay widget.

**Describe alternatives you've considered**
I used to use `ListTile` for this but when I saw this, I switched over, but its missing one of my main priorities/needs.

**Comment by Sandipkakadiya** [comment]
you can wrap `GFImageOverlay` inside `GestureDetector` or `InkWell` 
i.e,

```
InkWell (
     onTap: (){
            // do here, whateber you need
     },
     child: GFImageOverlay(),
),
```
