### ISSUE TITLE
GFCarousel ERROR

### ISSUE THREAD

**Issue by Bilonik** [ionicfirebaseapp/getwidget#185]
**Describe the bug**

Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:51605/dart_sdk.js:4332:11)
    at Object.nullCheck (http://localhost:51605/dart_sdk.js:4662:30)
    at page_view.PageController.new.nextPage (http://localhost:51605/packages/flutter/src/widgets/page_view.dart.lib.js:366:38)
    at http://localhost:51605/packages/getwidget/components/carousel/gf_carousel.dart.lib.js:1031:38
    at http://localhost:51605/dart_sdk.js:23808:9

**Comment by Bilonik** [comment]
#157

**Comment by Sandipkakadiya** [comment]
Could you please describe proper steps to reproduce this error.?

**Comment by Bilonik** [comment]
Hi @Sandipkakadiya 

` var pruebaList = [
          "https://images.freeimages.com/images/large-previews/7c7/tulips-1531279.jpg",
          "https://images.freeimages.com/images/large-previews/7c7/tulips-1531279.jpg",
          "https://images.freeimages.com/images/large-previews/7c7/tulips-1531279.jpg"
        ];
        return GFCarousel(
          viewportFraction: 1.00,
          autoPlay: true,
          pagination: false,
          height: height,
          items: pruebaList.map(
            (url) {
              return Container(
                margin: EdgeInsets.all(8.0),
                child: ClipRRect(
                  borderRadius: BorderRadius.all(Radius.circular(5.0)),
                  child: Image.network(
                          url,
                          fit: BoxFit.cover,
                          width: (MediaQuery.of(context).size.width).toDouble(),
                        )
                     
                ),
              );
            },
          ).toList(),
          onPageChanged: (index) {
            // setState(() {
            //   // index;
            // });
          },
        );`

**Comment by Bilonik** [comment]
flutter doctor -v 
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.23.0-7.0.pre at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision db6e2d8aa5 (7 days ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at /Users/alonhorovitz/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

**Comment by Bilonik** [comment]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] The following TypeErrorImpl was thrown building AnimatedBuilder(animation: PageController#83414(one
[        ] client, offset 11130000.0), dirty, state: _AnimatedState#cfa89):
[   +1 ms] Unexpected null value.
[   +2 ms] The relevant error-causing widget was:
[        ]   AnimatedBuilder
[        ]   **file:///usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/getwidget-1.2.2/lib/components/carousel/gf_carousel.dart:260:22**

**Comment by Bilonik** [comment]
Flutter Web

**Comment by Bilonik** [comment]
#196 Maybe is the same
