### ISSUE TITLE
Button Border Redius

### ISSUE THREAD

**Issue by vishwajit76** [ionicfirebaseapp/getwidget#186]
Provide an option in GFButton to change button border-radius using Box-Decoration.
Only this feature is missing in GFButton.
Thank you.

![WhatsApp Image 2020-09-24 at 11 22 59 PM](https://user-images.githubusercontent.com/25575802/94181372-04bd2480-febd-11ea-850f-e26d4ce7701d.jpeg)

**Comment by Sandipkakadiya** [comment]
Box decoration optionn is not available with GFButton but you can get similar result using Border radius.
