### ISSUE TITLE
[GFIconButton] Wrong touch area

### ISSUE THREAD

**Issue by zl910627** [ionicfirebaseapp/getwidget#195]
**Describe the bug**
`GFIconButton` does not detect tap event properly.

**To Reproduce**
Too long story and please check below screen record.
https://www.dropbox.com/s/my4gbswuwy1sfv7/Screen%20Recording%202020-10-08%20at%2013.54.29.mov?dl=0

**Expected behavior**
`GFIconButton` should be clickable for all splash area.

**Smartphone (please complete the following information):**
 - Simulator : Pixel-XL(android 31), iPhone X (iOS 14)
 - Real device : Samsung Galaxy, iPhone X.

**Comment by Sandipkakadiya** [comment]
This issue has been fixed in new release [1.2.3](https://pub.dev/packages/getwidget/versions/1.2.3)
