### ISSUE TITLE
GFSegmentedTab does not draw from ThemeData.colorScheme for its colors.

### ISSUE THREAD

**Issue by safield** [ionicfirebaseapp/getwidget#213]
To reproduce:
-define a ThemeData instance with a defined ColorScheme class.
-set that ThemeData on the top level MaterialApp
-observe that GFSegmentedTab does not draw from the colorScheme for its colors.

**Comment by deepikahr** [comment]
Hi, we are not currently using ThemeData colorscheme in any of our components. You can use tabBarColor property to change color of tabs. Thank you
