### ISSUE TITLE
Social Icons not found

### ISSUE THREAD

**Issue by Vakil-Parth** [ionicfirebaseapp/getwidget#216]
Can't get social icons and brand color

![Screenshot 2021-01-09 at 6 22 08 PM](https://user-images.githubusercontent.com/46394668/104092117-d9154d00-52a7-11eb-8220-c4aada952c4a.png)

`  GFButton(
    onPressed: (){},
    text: "primary",
    icon: Icon(Icons.share),
  ),`

Better if icon installation and list is provided.

**Comment by Purus** [comment]
Was looking to find this.. Thanks in advance.

**Comment by RahemanAli321** [comment]
i want to contribute your project as begginer so do you have any community that will helps me to contribute for this project

**Comment by Vakil-Parth** [comment]
after 6 months no reply

**Comment by Darrekt** [comment]
The documentation for the social button needs to be improved, the examples don't even use the GFSocialButton type. Hope this can be rectified soon. 

It is also not stated if we have to find the icon and colours ourselves, as the example hints that it is provided somehow. I've spent an hour looking around and concluded that they don't exist, which is _very_ misleading and a waste of developers' time.

**Comment by Vakil-Parth** [comment]
I have found way to make it work using [https://www.fluttericon.com/](https://www.fluttericon.com/).
hope you find it useful.

**Comment by PietechSolution** [comment]
We are working on docs to improve asap. We have updated docs you can follow now and see if that can help

https://docs.getwidget.dev/gf-button/social-button/
