### ISSUE TITLE
roadmap link is broken

### ISSUE THREAD

**Issue by Miamoto-Musashi** [ionicfirebaseapp/getwidget#217]
**Describe the bug**
[roadmap link](https://docs.getwidget.dev/#get-widget-roadmap) in [introduction page](https://docs.getwidget.dev/#get-widget-roadmap) shows apache message (Apache is functioning normally)

**To Reproduce**
1. Go to [introduction page](https://docs.getwidget.dev/#get-widget-roadmap)
2. Click on [roadmap link](https://docs.getwidget.dev/#get-widget-roadmap)
3. Scroll down to 'Top'
4. See error Apache is functioning normally

**Expected behavior**
Roadmap page

**Comment by Atul-pietech** [comment]
hello @Miamoto-Musashi 
Sorry for late replying, this was resolved.
