### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by leynier** [ionicfirebaseapp/getwidget#219]
Flutter 2 is released with null safety in stable version.

**Comment by leynier** [comment]
You need help with this support?

**Comment by PietechSolution** [comment]
Yes , We working on null safety support and expected to release next week including widget testing for all our components.

**Comment by leynier** [comment]
> Yes , We working on null safety support and expected to release next week including widget testing for all our components.

Awesome!!! Thanks very much for the quick response.
