### ISSUE TITLE
Icon Badge Position

### ISSUE THREAD

**Issue by kcchenkd** [ionicfirebaseapp/getwidget#221]
Hi,

I would like to display a simple circle badge on the topright corner of the icon (as shown Icons with Badges in https://docs.getwidget.dev/gf-badge/#badges)  but could not figure out how to move the "dot" from left to right.

Thanks.

GFIconBadge(
            child: Icon(icon),
            counterChild: const GFBadge(
              size: 16,
              shape: GFBadgeShape.circle,
           ))

**Comment by Vakil-Parth** [comment]
+1

**Comment by deepikahr** [comment]
Hi, above mentioned issue is fixed in getwidget version 2.0.4.
