### ISSUE TITLE
GFProgressBar  cause error: 

### ISSUE THREAD

**Issue by yg7001** [ionicfirebaseapp/getwidget#224]
getwidget 2.0.1-nullsafety.4
code:  GFProgressBar(percentage: 0.2,backgroundColor: Colors.red,progressBarColor: Colors.green,)

cause error: 
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building GFProgressBar(dirty, dependencies: [MediaQuery, _EffectiveTickerMode], state: _GFProgressBarState#33e14):
type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast

The relevant error-causing widget was: 
  GFProgressBar file:///D:/MobDev/projects/tds/lib/views/task_item_view.dart:33:13
When the exception was thrown, this was the stack: 
#0      _GFProgressBarState.build (package:getwidget/components/progress_bar/gf_progress_bar.dart:285:34)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)

**Comment by PietechSolution** [comment]
Please use the latest updated version and see if the issue continues or not.
