### ISSUE TITLE
GFCard : Null check operator used on a null value 

### ISSUE THREAD

**Issue by shubhamkatore** [ionicfirebaseapp/getwidget#229]

**Comment by fturhan** [comment]
I have the same issue since i updated my project to null-safety

**Comment by Ronjack** [comment]
same

**Comment by shubhamkatore** [comment]
@Sandipkakadiya Please release next version.

**Comment by rezashamdani** [comment]
i'm having the same problem

**Comment by PietechSolution** [comment]
We have updated packages,  please check with new version.

Thanks everyone please keep sharing valuable feedback to improve and add more widgets in packages.
