### ISSUE TITLE
ProgressBar cannot be full width widget.

### ISSUE THREAD

**Issue by nicejhkim** [ionicfirebaseapp/getwidget#232]
**Describe the bug**
Cannot make 100% width progressbar.

**To Reproduce**
GFProgressBar(
                              percentage: percent,
                              lineHeight: 3,
                              backgroundColor: Colors.black,
                              progressBarColor: Color(0xffe21c1c),
                              padding: EdgeInsets.zero,
                            )

**Expected behavior**
Should have margin option.
Progress Indicator always has fixed margins on both sides.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9

**Additional context**
GetWidget 2.0.2

**Comment by deepikahr** [comment]
Hi, above mentioned issue is fixed in getwidget version 2.0.4.
