### ISSUE TITLE
Error on Documentation for GF Intro Screen

### ISSUE THREAD

**Issue by awoyele** [ionicfirebaseapp/getwidget#239]
**Describe the bug**
Missing documentation. The documentation for the intro screen is incomplete. The first part (Part with Stateful widget) and the 2nd part (beginning of state) is not included in the documentation. I'll look around to see if I can find a fix and make a PR
Take a look at the code on this page:
https://docs.getwidget.dev/gf-intro-screen/

**To Reproduce**
1. Go to https://docs.getwidget.dev/gf-intro-screen/
2. Look at the beginning of code
3. Code is missing Stateful Widget declaration and State declaration

Related to #225 

**Expected behavior**
There should be a class that extends stateful widget

**Screenshots**
<img width="840" alt="Screen Shot 2021-08-03 at 11 46 13 PM" src="https://user-images.githubusercontent.com/16243076/128123611-dec0d10f-dd76-4dc0-8de1-286cf2345826.png">

**Comment by awoyele** [comment]
PR created in documentation https://github.com/ionicfirebaseapp/getwidget-docs/pull/28

**Comment by PietechSolution** [comment]
Thanks we have update Docs.
