### ISSUE TITLE
Issue with GFAccordion in showAccordion not expanding

### ISSUE THREAD

**Issue by bssam1996** [ionicfirebaseapp/getwidget#240]
**Describe the bug**
When changing the bool variable that showAccordion is assigned to, nothing happens.

**To Reproduce**
That's a sample of my code:
Outside the build: 
bool expanded = false;

inside the build:
Appbar....
actions: [
          TextButton(
              onPressed: (){
                setState(() {
                  expanded = !expanded;
                });
              },
              child: Text("Toggle All",style: TextStyle(color: Colors.white,fontSize: 20,fontWeight: FontWeight.bold),))
        ],

GFAccordion inside the body
return GFAccordion(
              titleBorder:Border.all(color: Colors.deepPurple[200],width: 2),
              titleBorderRadius: BorderRadius.all(Radius.circular(20)),
              showAccordion:expanded,
              titleChild: Center(child: Text(keydict,style: TextStyle(color:Colors.indigo,fontSize: 20,fontWeight: FontWeight.bold),),), ....

**Expected behavior**
Nothing happens when clicking on the TextButton (tried printing expanded value and it's changing as expected)

**Smartphone:**
 - Device: [Samsung S20+]
 - OS: [Android 10]

**Additional context**
Am using getwidget 2.0.3

**Comment by deepikahr** [comment]
Hi, we will add this in next build
