### ISSUE TITLE
Tab bar

### ISSUE THREAD

**Issue by Yosiwealth** [ionicfirebaseapp/getwidget#253]
is it possible to have the line at bottom of the icon and names o be at the top instead?
![image](https://user-images.githubusercontent.com/26458006/144488233-b09c797e-ccf8-40e9-a722-04451481a3e1.png)

**Comment by code-gene** [comment]
@Yosiwealth You can customize your way as tabs has datatype of List<Widget> so you define your widgets your way. You can customize indicator by using indicator properties like indicatorPadding, indicatorColor, indicatorWeight. Please read the documentation for details. 

Pasting the code below for reference,

```
bottomNavigationBar: GFTabBar(
  length: 3,
  controller: tabController,
  indicatorPadding: const EdgeInsets.only(left: 20, right: 20, bottom: 5),
  // indicator: BoxDecoration(
  //   border: Border(
  //     bottom: BorderSide(color: Colors.white, width: 2),
  //   ),
  // ),
  indicatorColor: Colors.white,
  indicatorWeight: 2.0,
  tabs: [
    Tab(
      child: Column(
        children: const [
          Text('Tab1'),
          SizedBox(height: 5),
          Icon(Icons.directions_bus),
        ],
      ),
    ),
    const Tab(
      icon: Icon(Icons.directions_bus),
      child: Text(
        "Tab2",
      ),
    ),
    const Tab(
      icon: Icon(Icons.directions_railway),
      child: Text(
        "Tab3",
      ),
    ),
  ],
),
```
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/72328725/150091565-f6fb4acf-38b1-4a1b-952d-f9c1d6fc4ca7.png)
