### ISSUE TITLE
How to have custom indicator/dots/pagination?

### ISSUE THREAD

**Issue by variablevariance** [ionicfirebaseapp/getwidget#255]
I want to make my own dots, the only option I can find is indicator color and size. I want to make a transparent dot with white border for passiveIndicator.

**Comment by code-gene** [comment]
@variablevariance You can now also add border to the dots. Please check the below code.

```
activeIndicator: Colors.white,
activeDotBorder: Border.all(color: Colors.blue, width: 5),
passiveIndicator: Colors.transparent,
passiveDotBorder: Border.all(color: Colors.white, width: 5),

```
