### ISSUE TITLE
in the future， Will add About textfield widget

### ISSUE THREAD

**Issue by herowws** [ionicfirebaseapp/getwidget#256]
in the future， Will add About textfield widget

**Comment by code-gene** [comment]
@herowws Please be more verbose

**Comment by sharanAmit** [comment]
Support of AutoSizeTextField feature. https://pub.dev/packages/auto_size_text_field.
Please don't use this package as dependency, What I liked about this get_widget is that it has no any external dependency and I think it continue this.
