### ISSUE TITLE
GFCarousel

### ISSUE THREAD

**Issue by idolevi99** [ionicfirebaseapp/getwidget#268]
**Describe the bug**

hi, I'm using your library and I'm having a problem.  I use GFCarousel and I can not update the pagination while running, the points do not change depending on the image displayed on the screen, it stays stuck, can you please give an example of how to use it correctly and that the points will change during running?  Thank you.

**Comment by code-gene** [comment]
@idolevi99 

Can you provide your code example, for my case it is working fine the points are working fine. Please follow the example below. If need any help to understand feel free to ask.

`GFCarousel(
  initialPage: 0,
  hasPagination: true,
  pagerSize: 10,
  activeIndicator: Colors.green,
  passiveIndicator: Colors.white,
  items: imageList.map(
    (url) {
      return Container(
        margin: EdgeInsets.all(8.0),
        child: ClipRRect(
          borderRadius: BorderRadius.all(Radius.circular(5.0)),
          child: Image.network(url, fit: BoxFit.cover, width: 1000.0),
        ),
      );
    },
  ).toList(),
  onPageChanged: (index) {
    setState(() {
      index;
    });
  },
),`
