### ISSUE TITLE
GF Introduction Screen examples are missing: showIntroScreenBottomNavigationBar: true

### ISSUE THREAD

**Issue by UnicornaasTech** [ionicfirebaseapp/getwidget#270]
The examples on https://docs.getwidget.dev/gf-intro-screen/ are missing one important line of code:
showIntroScreenBottomNavigationBar: true

Without this, the examples do not show the navigator, even though it's specified in the examples.

Add the line here:

Widget build(BuildContext context) {
  return SafeArea(
    child: GFIntroScreen(
      color: Colors.blueGrey,
      slides: slides(),
      pageController: _pageController,
      currentIndex: inittialIndex,
      pageCount: 5,
      showIntroScreenBottomNavigationBar: true,                     <= ADD THIS LINE
      introScreenBottomNavigationBar: GFIntroScreenBottomNavigationBar(
        pageController: _pageController,

**Comment by krishna-pietech** [comment]
@UnicornaasTech we will soon update the docs.

**Comment by Atul-pietech** [comment]
Hi @UnicornaasTech please update the getWidget version, 
The example is working with the latest getWidget version.
By default it will show the navigation bar until you set showIntroScreenBottomNavigationBar to 'false'
