### ISSUE TITLE
gf_progress_bar linearGradient 

### ISSUE THREAD

**Issue by ToZhanChi** [ionicfirebaseapp/getwidget#271]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

url: https://github.com/ionicfirebaseapp/getwidget/blob/master/lib/components/progress_bar/gf_progress_bar.dart

if (linearGradient != null) {
      throw ArgumentError(' linearGradient cannot be given');
}

**Comment by krishna-pietech** [comment]
Hi @zhanchi88 , can you explain about the issue ?

**Comment by shichunlei** [comment]
linearGradient can not work


`GFProgressBar(
                                      lineHeight: 18,
                                      linearGradient: LinearGradient(
                                          colors: [const Color(0xffF3201E), Color(0xfff4320f)]),
                                      backgroundColor: const Color(0xfff6f6f6),
                                      percentage: 0.8,
                                      animation: true,
                                      child: Center(
                                          child: Text(
                                              "80%",
                                              style: TextStyle(color: Colors.grey, fontSize: 13))))
`





======== Exception caught by widgets library =======================================================
The following ArgumentError was thrown building Consumer<AssistedDetailModel>(dirty, dependencies: [_LocalizationsScope-[GlobalKey#47197], _InheritedTheme, _InheritedProviderScope<AssistedDetailModel?>]):
Invalid argument(s):  linearGradient cannot be given

**Comment by ToZhanChi** [comment]
> 嗨@zhanchi88，你能解释一下这个问题吗？



> linearGradient can not work
> 
> GFProgressBar( lineHeight: 18, linearGradient: LinearGradient( colors: [const Color(0xffF3201E), Color(0xfff4320f)]), backgroundColor: const Color(0xfff6f6f6), percentage: 0.8, animation: true, child: Center( child: Text( "80%", style: TextStyle(color: Colors.grey, fontSize: 13))))
> 
> ======== Exception caught by widgets library ======================================================= The following ArgumentError was thrown building Consumer(dirty, dependencies: [_LocalizationsScope-[GlobalKey#47197], _InheritedTheme, _InheritedProviderScope<AssistedDetailModel?>]): Invalid argument(s): linearGradient cannot be given

**Comment by ToZhanChi** [comment]
> Hi @zhanchi88 , can you explain about the issue ?

https://github.com/ionicfirebaseapp/getwidget/blob/9fcb362f37fa539d62643975af58f9fe876b4841/lib/components/progress_bar/gf_progress_bar.dart#L34

**Comment by Atul-pietech** [comment]
hi, @ToZhanChi 
Please update the getwidget version and check.
I am not able to reproduce the issue, It is seems to be a state related  issue.
Your code works fine with **getwidget versoin 3.0.1**

**GFProgressBar(
lineHeight: 18,
linearGradient: LinearGradient(
colors: [const Color(0xffF3201E), Color(0xfff4320f)]),
backgroundColor: const Color(0xfff6f6f6),
percentage: 0.8,
animation: true,
child: Center(
child: Text(
"80%",
style: TextStyle(color: Colors.grey, fontSize: 13))))**

**Comment by Atul-pietech** [comment]
Hi @ToZhanChi sorry we could not reply you,
I have checked your code with flutter version 3.0.1 and getwidget version 3.0.1 , this is working fine.
**_GFProgressBar(
lineHeight: 18,
linearGradient: LinearGradient(
colors: [const Color(0xffF3201E), Color(0xfff4320f)]),
backgroundColor: const Color(0xfff6f6f6),
percentage: 0.8,
animation: true,
child: Center(
child: Text(
"80%",
style: TextStyle(color: Colors.grey, fontSize: 13))))_**


<img width="777" alt="image" src="https://user-images.githubusercontent.com/111724591/204739427-6a282d98-63c4-4361-acd3-a0dccb1e15b9.png">
