### ISSUE TITLE
Border radius doesn't apply on splash effect when clicking on buttons

### ISSUE THREAD

**Issue by mohamad97-alhomsi** [ionicfirebaseapp/getwidget#272]
in many widgets, if I chose the rounded shape for buttons like checkboxes or  Accordion widgets the splash effect still has the square shape and doesn't take the circular shape seems it need to be clipped as the child shape.
Please notice the screenshots
![Screenshot_6](https://user-images.githubusercontent.com/71252098/159654532-a0bfcbd8-78a2-46d4-8861-5b665dd8ce69.png)
![Screenshot_5](https://user-images.githubusercontent.com/71252098/159654550-63d978c1-b649-4a27-9eea-126fbfc92845.png)

**Comment by krishna-pietech** [comment]
Hi @mohamad97-alhomsi , we are looking in to this. Will be resolved in next release
