### ISSUE TITLE
textfield

### ISSUE THREAD

**Issue by herowws** [ionicfirebaseapp/getwidget#279]
![image](https://user-images.githubusercontent.com/41428542/165436036-8d990003-234e-4ddc-a84b-5dacdccc4da2.png)
![image](https://user-images.githubusercontent.com/41428542/165436059-1c3123b3-e8e9-49ab-ae8e-d8c8d345a9e0.png)
![image](https://user-images.githubusercontent.com/41428542/165436104-a781d4d8-50ca-40dd-a75a-c3784d69973d.png)
![image](https://user-images.githubusercontent.com/41428542/165436166-80cac6ba-3006-4ef1-8725-44ffee9f86e1.png)
A project requires a variety of textfiled styles

**Comment by Arunbalaji001** [comment]
@herowws A new version v3..0.1 has been released with these features implemented, Kindly check
