### ISSUE TITLE
GFMultiSelect initial state

### ISSUE THREAD

**Issue by Nashati** [ionicfirebaseapp/getwidget#280]
**Is your feature request related to a problem? Please describe.**
It seems that `GFMultiSelect` doesn't have an initial state. I didn't figure out how to create a multi-select widget with some options that are already checked.

**Describe the solution you'd like**
It would be nice to add a `selected` list that indicates which option should be selected at initialization.

**Comment by Arunbalaji001** [comment]
@Nashati The feature you have requested has been added in the new version, kindly check
