### ISSUE TITLE
Not Able to run application in latest Flutter Version 3.0.0

### ISSUE THREAD

**Issue by devalp-pro** [ionicfirebaseapp/getwidget#281]
**Describe the bug**
Not able to run the application with the latest version of flutter. Getting Below compile-time error.

/C:/Users/Deval/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/getwidget-2.0.5/lib/components/sticky_header/gf_sticky_header_builder.dart:63:28: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Users/Deval/AppData/Local/Flutter/flutter/packages/flutter/lib/src/widgets/binding.dart').
            WidgetsBinding.instance?.endOfFrame.then((_) {
                           ^
/C:/Users/Deval/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Deval\AppData\Local\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Deval\AppData\Local\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1

**Flutter Doctor**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.67.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by kpk-i710** [comment]
yes, also the problem is running on 3.0

**Comment by SalahCheihbi** [comment]
There is no update for this version 3.0.0

**Comment by Arunbalaji001** [comment]
@devalp-pro , @SalahCheihbi New update for GetWidget has been releasesed
