### ISSUE TITLE
Enhance GFList tile to include a row of optional text buttons at the bottom

### ISSUE THREAD

**Issue by ivansempijja** [ionicfirebaseapp/getwidget#300]
**Is your feature request related to a problem? Please describe.**
 This is just a suggest enhancement on the GF List tile

**Describe the solution you'd like**
Would like to have an option on the GFList tile to have a row of at least two text button or tags in the bottom row

**Describe alternatives you've considered**
I have explored using the card, option and I still find/think it would be neater to have this functionality has party of the GF List tile 

**Additional context**
<img width="381" alt="Screenshot 2022-10-26 at 2 12 24 AM" src="https://user-images.githubusercontent.com/19774829/197899099-38869e19-ff65-4e70-b66b-445c32ca451d.png">

**Comment by Atul-pietech** [comment]
@ivansempijja 
Thank you for your suggestion.

**Comment by sarithavarrier** [comment]
@ivansempijja ,Please use the latest version, we have included two optional buttons for GFList tile
