### ISSUE TITLE
It is suggested to establish Chinese documents and provide demo APK

### ISSUE THREAD

**Issue by zhaoxiuyu** [ionicfirebaseapp/getwidget#302]
建立中文文档并提供演示APK

**Comment by Atul-pietech** [comment]
Hi @zhaoxiuyu ,
following is the link of getwidget demo APP on play store,
https://play.google.com/store/apps/details?id=dev.getflutter.appkit,

for documentation you can follow
https://docs.getwidget.dev/ (Please use web translation feature to translate the text into Chinese.)

**Comment by krishna-pietech** [comment]
@zhaoxiuyu We will be so happy if you contribute. Closing for now.
