### ISSUE TITLE
Unable to load asset: icons/google.png

### ISSUE THREAD

**Issue by khalid5555** [ionicfirebaseapp/getwidget#303]
Error while trying to load an asset: Failed to load asset at "assets/icons/google.png" (404)
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: icons/google.png
When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/flutter/src/services/asset_bundle.dart 258:7                                                                      load
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Image provider: AssetImage(bundle: null, name: "icons/google.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#1514c(), name: "icons/google.png", scale:
  1)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Atul-pietech** [comment]
hi @khalid5555 ,
This does not seem to be a getwidget issue, you can raise here in related git repo.

**Comment by gantanikhilraj** [comment]
is it fixed? if not can assign to me

**Comment by Atul-pietech** [comment]
Hi, @khalid5555 Please check
https://github.com/ionicfirebaseapp/getwidget/issues/313
