### ISSUE TITLE
Progress Bar Manually drag progress

### ISSUE THREAD

**Issue by zhaoxiuyu** [ionicfirebaseapp/getwidget#305]
New progress bar dragging function, similar to slider?

**Comment by Atul-pietech** [comment]
Can you elaborate please, are you  requesting functionality like slider in progress bar?

**Comment by zhaoxiuyu** [comment]
Similar to playback progress or volume adjustment, you can manually drag to change the value.

**Comment by Atul-pietech** [comment]
hi, @zhaoxiuyu thank you for this suggestion , we would look into this.

**Comment by sarithavarrier** [comment]
@zhaoxiuyu ,we have included option(isDragable: true,) to make the progressbar draggable manually in latest version
Thank you
