### ISSUE TITLE
Target of URI doesn't exist: 'package:getwidget/getwidget.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

### ISSUE THREAD

**Issue by lude1994** [ionicfirebaseapp/getwidget#306]
getwidget: ^2.0.4
引入import 'package:getwidget/getwidget.dart';报错

**Comment by Atul-pietech** [comment]
hi, @lude1994 
I tried to reproduced this, I did not get any error,
Please check that you properly declare the plugin in pubspec.yaml file,
also make sure you use command **flutter pub get**
