### ISSUE TITLE
GFToggle disabledText 显示不全

### ISSUE THREAD

**Issue by zhaoxiuyu** [ionicfirebaseapp/getwidget#309]
**Describe the bug**
GFToggle disabledText 显示不全

**To Reproduce**
    return GFToggle(
      onChanged: (v) {
        updateGFToggle(v);
      },
      value: gfToggleValue,
      type: GFToggleType.android,
      enabledText: '千米',
      disabledText: '英尺',
    );

**Expected behavior**
我希望文本能完全显示

**Screenshots**
![1675050977509](https://user-images.githubusercontent.com/16554580/215384358-4cbe96af-497d-4f64-8ac1-ed12e4fee327.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Android]
 - Version [e.g. 2.1.1]

**Smartphone (please complete the following information):**
 - Device: [e.g. 小米11U]
 - OS: [e.g. Android12]

**Comment by Atul-pietech** [comment]
Thank you @zhaoxiuyu for updating us about this, our team will look into this.

**Comment by Atul-pietech** [comment]
Hi @zhaoxiuyu , right now we are not showing whole text instead you can try to set font size bit smaller.
that will make this done for you.
