### ISSUE TITLE
GFMultiSelect validator and focusnode.

### ISSUE THREAD

**Issue by manasrathod** [ionicfirebaseapp/getwidget#310]
It seems that GFMultiSelect doesn't have an validator (ex. must have to choose one value while using with forms) and focusnode.

**Comment by Atul-pietech** [comment]
Thank you @manasrathod  for updating us about this, our team will look into this.

**Comment by yash-pietech** [comment]
Hello @manasrathod 

- I reviewed the code and we are sending the data of selectedIndex on the onSelect callback in our widget.
- so you can use these values and add the validation logic as you want because as with different user of this library their needs are also different for validation .
