### ISSUE TITLE
Social login button documentation is incorrect

### ISSUE THREAD

**Issue by lukehutch** [ionicfirebaseapp/getwidget#311]
The code on the following page does not produce the buttons in the screenshots. It looks like the code was copied/pasted multiple times as a placeholder, and never completed.

https://docs.getwidget.dev/gf-button/social-button/

**Comment by Atul-pietech** [comment]
Thank you @lukehutch for updating about this our team will check this out.

**Comment by yash-pietech** [comment]
Hi @lukehutch 
I checkout the document and also tried all examples . I did not find any issue so would you please more describe what exactly the issue you are facing .
<img width="340" alt="image" src="https://user-images.githubusercontent.com/126047746/222101813-e36254fe-741d-45b4-a2b3-3ea4caca3001.png">

**Comment by lukehutch** [comment]
Hi, thanks for trying the examples, and sorry for the time you spent on this, given that the code works! I must have been doing something wrong. I will close this.
