### ISSUE TITLE
component image is missing in documentation

### ISSUE THREAD

**Issue by Miamoto-Musashi** [ionicfirebaseapp/getwidget#337]
**Describe the bug**
all images in documentation are broken

**To Reproduce**
1. Go to [docs](https://docs.getwidget.dev/)
2. Click on any item
3. Scroll  to Top
4. See missing images of the component and the icon for missing images

**Expected behavior**
images representing the component should be present

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOs
 -  Browser: Edge

**Additional context**
images will help make the documentation complete
<img width="695" alt="Screenshot 2023-08-04 alle 01 39 11" src="https://github.com/ionicfirebaseapp/getwidget/assets/283196/a683f7c9-9eee-40ad-b698-852079fd1a2e">

**Comment by hajajmaor** [comment]
My comment in the website repo
#https://github.com/ionicfirebaseapp/getwidget-docs/issues/37#issuecomment-1680354439

> The image has incorrect links. in the MDs here, the src is: https://ik.imagekit.io/ionicfirebaseapp... In the website source code, the links are: https://image.ionicfirebaseapp.com/getwidget/.....

**Comment by avlobn** [comment]
and my last comment 
https://github.com/ionicfirebaseapp/getwidget-docs/issues/37#issuecomment-1692126315
