### ISSUE TITLE
Spelling of 'accordion' is incorrect

### ISSUE THREAD

**Issue by aivantuquero** [ionicfirebaseapp/getwidget#348]
In pubdev package page of getwidget, the 'accordion' is mistakenly spelled as 'accordian' which can be misleading.
![image](https://github.com/ionicfirebaseapp/getwidget/assets/54162088/8d225a8c-3713-4be0-b899-38d0b354cb0f)

![image](https://github.com/ionicfirebaseapp/getwidget/assets/54162088/1939655e-e7d3-4841-ba59-a7cde47f862b)

**Comment by ashwinnavange** [comment]
fixed in #349
