### ISSUE TITLE
flutter 3.27 compile error 

### ISSUE THREAD

**Issue by Santhosh-4035** [ionicfirebaseapp/getwidget#357]
Describe the bug
After upgrading to flutter 3.27 the code fails to compile on android , using flutter build apk

Platform
 Android
 iOS

Error Log:
![image](https://github.com/user-attachments/assets/c161ff19-1bdf-4afa-9eb4-ac3ad6d9053d)

Flutter Version details

[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale
    en-EG)
    • Flutter version 3.27.0 on channel stable at
      /Users/AbdelazizMahdy/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (25 hours ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/AbdelazizMahdy/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.2.0.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 242.20629

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!

Have a look at this @atul-vashisht

**Comment by creacrea** [comment]
![2024-12-13_05-36-53](https://github.com/user-attachments/assets/476f42fc-d451-4e3d-b241-fb0a8c2010b0)

**Comment by ngfchl** [comment]
I am also see this error。in local change line `final CardTheme cardTheme` to `final cardTheme`，but it's not work in cloud compile

**Comment by mrniamster** [comment]
have the same error, please release the update

**Comment by krishna-pietech** [comment]
Fix was released.
